default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Gvents_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: Gvents_test

production:
  <<: *default
  database: Gvents_production
  url: <%= ENV['DATABASE_URL'] %>
